---
# defaults file for epmon
distro_lookup_path:
  - "{{ ansible_facts.distribution }}.yaml"
  - "{{ ansible_facts.os_family }}.yaml"
  - "main.yaml"

epmon_os_user: "apimon"
epmon_os_group: "apimon"
epmon_systemd_service_name: "apimon-epmon.service"
epmon_systemd_unit_path: "{{ ('/etc/systemd/system/'+ epmon_systemd_service_name) }}"
epmon_image: "quay.io/opentelekomcloud/apimon"
epmon_config_dir: "/etc/apimon"
epmon_config_file_name: "apimon-epmon.yaml"
epmon_secure_config_file_name: "apimon-epmon-secure.yaml"
# epmon_config:
# epmon_secure_config:
epmon_container_name: "apimon_epmon"

container_command: "podman"
container_runtime: "/usr/bin/{{ container_command }}"
