---
# tasks file for scheduler

- name: Include Fedora variables
  include_vars: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install required packages
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  register: task_result
  until: task_result is success
  retries: 5

- include_tasks: firewall.yml

- name: Create scheduler group
  become: yes
  group:
    name: "{{ scheduler_os_group }}"
    state: present

- name: Create scheduler user
  become: true
  user:
    name: "{{ scheduler_os_user }}"
    group: "{{ scheduler_os_group }}"
    state: present

- name: Write Scheduler Systemd unit file
  become: true
  template:
    src: apimon_scheduler.service
    dest: "{{ scheduler_systemd_unit_path }}"

- name: Create required directories
  become: true
  file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "{{ scheduler_os_user }}"
    group: "{{ scheduler_os_group }}"
    recurse: true
  loop:
    - {dest: "/var/log/apimon"}
    - {dest: "/var/lib/apimon"}
    - {dest: "{{ scheduler_config_dir }}"}
    - {dest: "/home/{{ scheduler_os_user }}/tmp"}

- name: Write env
  become: true
  become_user: "{{ scheduler_os_user }}"
  template:
    src: env_scheduler
    dest: "{{ scheduler_config_dir }}/env_scheduler"
  notify:
    - restart scheduler

- name: Write logging.conf
  become: true
  become_user: "{{ scheduler_os_user }}"
  template:
    src: logging.conf
    dest: "{{ scheduler_config_dir }}/logging.conf"
  notify:
    - restart scheduler

- name: Write scheduler config
  become: true
  become_user: "{{ scheduler_os_user }}"
  template:
    src: apimon.yaml
    dest: "{{ scheduler_config_dir }}/apimon.yaml"
  notify:
    - restart scheduler
