---
# defaults file for scheduler
scheduler_os_group: apimon
scheduler_os_user: apimon
scheduler_systemd_service_name: apimon_scheduler.service
scheduler_systemd_unit_path: "{{ ('/etc/systemd/system/' + scheduler_systemd_service_name ) }}"
scheduler_config_dir: /etc/apimon
scheduler_image: otcinfra/apimon
scheduler_config:
executor_image: otcinfra/apimon
