---
# defaults file for scheduler
distro_lookup_path:
  - "{{ ansible_facts.distribution }}.yaml"
  - "{{ ansible_facts.os_family }}.yaml"
  - "main.yaml"

scheduler_os_group: "apimon"
scheduler_os_user: "apimon"
scheduler_systemd_service_name: "apimon-scheduler.service"
scheduler_systemd_unit_path: "{{ ('/etc/systemd/system/' + scheduler_systemd_service_name ) }}"
scheduler_image: "quay.io/opentelekomcloud/apimon"
scheduler_config_dir: "/etc/apimon"
scheduler_config_file_name: "apimon.yaml"
scheduler_secure_config_file_name: "apimon_secure.yaml"
scheduler_config:
scheduler_secure_config:
scheduler_container_name: "apimon_scheduler"

container_command: "podman"
container_runtime: "/usr/bin/{{ container_command }}"
