---
# Playbook to install epmon
#

- name: Provision epmon
  hosts: epmon
  become: true
  gather_facts: true
  serial: 1
  roles:
    - opentelekomcloud.common.server
    - opentelekomcloud.apimon.epmon
  tasks:
  tags: epmon
